"""What each rules-support label ACTUALLY demands, once chunking is accounted for.

    python scripts/audit_rules_support_labels.py --output docs/r3-rules-support-audit.md

A conjunction of four rules sounds twice as strict as one of two. It is not, if
three of the four live in one chunk — retrieval returns chunks, so a rule that
shares a chunk with another scored rule cannot independently fail. It is then
not a requirement, and a verdict reporting it as covered overstates what was
measured. The same collapse can neuter a disjunction: an alternative sharing a
chunk with a required rule is satisfied automatically, and whatever proposition
it was meant to carry is never tested.

The labelling panel's completeness critic found both in half of the first ten
labels. This turns that into a check that runs, because the finding is a
property of the label crossed with the chunker and not a matter of opinion.

It changes nothing and it ratifies nothing.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from sabermetrics.assistant.eval.rules_support import (
    load_rules_support_labels,
    normalize,
    quote_problems,
    strictness_report,
)
from sabermetrics.reference_layer.chunker import DocumentChunker

ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "data" / "reference" / "comprehensive_rules"


def main() -> int:
    """Report every label's real bar and every rule that cannot fail."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    labels = load_rules_support_labels()
    if labels is None:
        raise SystemExit("AUDIT REFUSED: no rules-support labels are checked in")
    directory = SOURCE_DIR / labels.derived_from.effective_date.isoformat()
    source = directory / "normalized.txt"
    if not source.is_file():
        raise SystemExit(f"AUDIT REFUSED: {source} is not provisioned")
    text = source.read_text(encoding="utf-8")
    bodies = [
        normalize(chunk.content)
        for chunk in DocumentChunker().chunk_comprehensive_rules(source)
    ]

    reports = {
        label.question_id: strictness_report(label, bodies) for label in labels.labels
    }
    bars = [report["minimum_distinct_chunks"] for report in reports.values()]
    inert_rules = {
        question_id: report["required_rules_that_cannot_independently_fail"]
        for question_id, report in reports.items()
        if report["required_rules_that_cannot_independently_fail"]
    }
    inert_disjunctions = {
        question_id: report["inert_alternative_groups"]
        for question_id, report in reports.items()
        if report["disjunction_is_inert"]
    }
    unlocatable = {
        question_id: report["rules_in_no_chunk"]
        for question_id, report in reports.items()
        if report["rules_in_no_chunk"]
    }

    lines = [
        "# What the rules-support labels actually demand",
        "",
        "Generated by `scripts/audit_rules_support_labels.py`. Changes nothing,",
        "ratifies nothing.",
        "",
        f"- label set `{labels.label_set}`, status `{labels.status}`",
        f"- against {labels.derived_from.document} effective "
        f"{labels.derived_from.effective_date}, {len(bodies)} chunks",
        f"- quote problems: **{len(quote_problems(labels, text))}**",
        "",
        "## The bar is not the same across questions",
        "",
        f"A passing answer needs between **{min(bars)}** and **{max(bars)}**",
        "distinct chunks depending on the question. Any aggregate over these ten",
        '— including a headline "n of 10" — therefore mixes bars that differ by',
        f"a factor of {max(bars) / min(bars):.0f}.",
        "",
        "| question | verification | min chunks | required | any-of "
        "(groups/rules) | required rules that cannot independently fail | "
        "inert groups |",
        "|---|---|---:|---:|---:|---|---|",
    ]
    for label in labels.labels:
        report = reports[label.question_id]
        cannot = report["required_rules_that_cannot_independently_fail"]
        auto = [
            " or ".join(f"`{rule}`" for rule in group)
            for group in report["inert_alternative_groups"]
        ]
        lines.append(
            f"| {label.question_id} | {label.verification} | "
            f"{report['minimum_distinct_chunks']} | {len(label.required_rules)} | "
            f"{len(label.sufficient_any_of)}/{len(label.alternative_rules)} | "
            f"{', '.join(f'`{r}`' for r in cannot) if cannot else '—'} | "
            f"{'; '.join(auto) if auto else '—'} |"
        )
    lines += [
        "",
        "## What a reviewer has to decide",
        "",
        "**A rule that cannot fail is not a requirement.** Where one is listed",
        "above, the label's conjunction is shorter than it looks and the verdict",
        "reports the rule as covered when what came back was its chunk-mate.",
        "",
        "**An inert disjunction carries no constraint.** Where one is listed, the",
        "proposition the alternatives were chosen to establish is never tested —",
        "and in the labels flagged here that proposition is one the label's own",
        "`sufficient_support` prose calls mandatory.",
        "",
        "Neither is fixable by this script. Both need a decision about what the",
        "question demands, which is the owner's, and both are recorded here so",
        "that decision is made deliberately rather than discovered later.",
        "",
        f"- required rules that cannot independently fail: "
        f"**{sum(len(v) for v in inert_rules.values())}** across "
        f"{len(inert_rules)} labels",
        f"- inert disjunctions: **{len(inert_disjunctions)}** labels",
        f"- scored rules in no chunk at all: "
        f"**{sum(len(v) for v in unlocatable.values())}**"
        + (" — these can never be covered by any answer" if unlocatable else ""),
        "",
        "See `docs/r3-rules-support-critique.md` for the panel critic's",
        "per-label reading, including which labels it would ratify soonest.",
    ]
    report_text = "\n".join(lines) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report_text, encoding="utf-8")
        print(f"wrote {args.output}")
    else:
        print(report_text)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, RuntimeError, ValueError, KeyError) as exc:
        print(f"AUDIT REFUSED: {exc}")
        raise SystemExit(2) from None
